### ISSUE TITLE
Are these Cipher_Suites still updated?

### ISSUE THREAD

**Issue by mdantonio** [april/tls-table#4]
Hello,
I was looking at:
https://wiki.mozilla.org/Security/Cipher_Suites

and noticed that the table was last updated in May 2019 

I tried to execute the tsl-table script by myself but I got an error:

```
$ python3 tls-table.py mediawiki --colorize

Retrieving IANA cipher List
Retrieving NSS cipher list
  Warning: code point 0x00,0x66 (TLS_DHE_DSS_WITH_RC4_128_SHA) not in IANA registry
  Warning: code point 0x00,0x62 (TLS_RSA_EXPORT1024_WITH_DES_CBC_SHA) not in IANA registry
  Warning: code point 0x00,0x64 (TLS_RSA_EXPORT1024_WITH_RC4_56_SHA) not in IANA registry
  Warning: code point 0x00,0x63 (TLS_DHE_DSS_EXPORT1024_WITH_DES_CBC_SHA) not in IANA registry
  Warning: code point 0x00,0x65 (TLS_DHE_DSS_EXPORT1024_WITH_RC4_56_SHA) not in IANA registry
Retrieving OpenSSL cipher list
Unable to retrieve or parse OpenSSL cipher list
Retrieving GnuTLS cipher list
  Warning: code point 0x00,0x66 (TLS_DHE_DSS_ARCFOUR_128_SHA1) not in IANA registry
  Warning: code point 0xc1,0x02 (TLS_GOSTR341112_256_28147_CNT_IMIT) not in IANA registry


Retrieving cipher suites from Mozilla Server Side TLS page
Traceback (most recent call last):
  File "tls-table.py", line 259, in <module>
    get_colorize_chart()
  File "tls-table.py", line 68, in get_colorize_chart
    'Modern': get_colorize_chart_openssl_ciphers(recommendations[0]),
IndexError: list index out of range
```

Is this script still supported?
Can the wiki table still be considered updated? or can it be updated?

Many thanks for your support!

**Comment by noraj** [comment]
I think yes, eg IANA was updated on 2021-04-02

https://github.com/april/tls-table/blob/169f749c0371c73cf96f96d0b7a7e2c9e733f6b1/tls-table.py#L13

GNUTLS and OPENSSL are fetched form master branches so they should be updated.

https://github.com/april/tls-table/blob/169f749c0371c73cf96f96d0b7a7e2c9e733f6b1/tls-table.py#L12
https://github.com/april/tls-table/blob/169f749c0371c73cf96f96d0b7a7e2c9e733f6b1/tls-table.py#L16

**Comment by mdantonio** [comment]
Ok... thank you
Unfortunately the page at https://wiki.mozilla.org/Security/Cipher_Suites is not updated since the last two years and the script does not work for me

**Comment by noraj** [comment]
> Ok... thank you
> Unfortunately the page at https://wiki.mozilla.org/Security/Cipher_Suites is not updated since the last two years and the script does not work for me

You can see with #5 that TLS table is not working in it's actual state. I made a new tool called [TLS map](https://github.com/sec-it/tls-map) that you cloud use and will work to get up to date values.

**Comment by janbrasna** [comment]
The page https://wiki.mozilla.org/Security/Cipher_Suites is currently being updated manually, see:
- https://github.com/mozilla/server-side-tls/issues/292
- https://github.com/mozilla/server-side-tls/issues/247

**Comment by gstrauss** [comment]
Please see linked issues above for reference.

* The table on the wiki has been manually updated. https://wiki.mozilla.org/Security/Cipher_Suites
* The tls-table repository has been transferred to the mozilla organization.
* The tls-table repository has been updated to address the known issues.

If you find something amiss, please file a new issue.  Thanks!
